// ============ 控制目标表单 ============
// 创建/编辑控制目标
// 支持五维标签配置、标准动作设置

import React, { useState, useCallback, useEffect, useMemo } from "react";
import {
  ArrowLeft,
  Save,
  Plus,
  Trash2,
  AlertCircle,
  CheckCircle,
  Clock,
  Target,
  Layers,
  Scale,
  Sparkles,
  Search,
  Shield,
  ChevronDown,
  ChevronUp,
} from "lucide-react";
import { Button } from "../ui/button";
import { Input } from "../ui/input";
import { Badge } from "../ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "../ui/card";
import { ScrollArea } from "../ui/scroll-area";
import { toast } from "sonner";
import type {
  ControlObjective,
  ControlCategory,
  ActionRequirement,
  ActionPriority,
  FiveDimensionalTags,
} from "../../types";
import {
  generateControlObjectiveCode,
  previewControlObjectiveCode,
} from "../../services/codeGenerator";

// 控制类别选项
const CATEGORY_OPTIONS: { value: ControlCategory; label: string; desc: string }[] = [
  { value: "预防性", label: "预防性", desc: "防止事件发生的控制" },
  { value: "检测性", label: "检测性", desc: "发现已发生事件的控制" },
  { value: "纠正性", label: "纠正性", desc: "修复已造成损害的控制" },
  { value: "管理性", label: "管理性", desc: "政策、流程、培训" },
  { value: "技术性", label: "技术性", desc: "加密、访问控制、审计日志" },
  { value: "物理性", label: "物理性", desc: "门禁、监控、环境安全" },
];

// 重要性选项
const IMPORTANCE_OPTIONS = [
  { value: "critical", label: "核心", desc: "必须实施的关键控制" },
  { value: "high", label: "高", desc: "强烈建议实施" },
  { value: "medium", label: "中", desc: "根据实际情况实施" },
  { value: "low", label: "低", desc: "可选实施" },
];

// 优先级选项
const PRIORITY_OPTIONS: { value: ActionPriority; label: string }[] = [
  { value: "critical", label: "关键" },
  { value: "high", label: "高" },
  { value: "medium", label: "中" },
  { value: "low", label: "低" },
];

// 控制域选项
const DOMAIN_OPTIONS = [
  "数据安全",
  "个人信息保护",
  "网络安全",
  "应用安全",
  "物理安全",
  "业务连续性",
  "合规管理",
  "风险管理",
];

interface ControlObjectiveFormProps {
  initialData?: Partial<ControlObjective>;
  onSubmit: (data: ControlObjective) => void;
  onCancel: () => void;
  mode: "create" | "edit";
}

export function ControlObjectiveForm({
  initialData,
  onSubmit,
  onCancel,
  mode,
}: ControlObjectiveFormProps) {
  const [formData, setFormData] = useState<Partial<ControlObjective>>({
    code: "",
    name: "",
    nameEn: "",
    description: "",
    category: "管理性",
    domain: "数据安全",
    importance: "high",
    baseWeight: 5,
    status: "active",
    version: "1.0",
    applicableTags: {
      objects: [],
      subjects: [],
      lifecycles: [],
      securities: [],
      actions: [],
    },
    standardActions: [],
    mappedClauses: [],
    mappedClauseCount: 0,
    applicableScenarios: [],
    scenarioCount: 0,
    ...initialData,
  });

  const [expandedSection, setExpandedSection] = useState<string>("basic");
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [isCodeManuallyEdited, setIsCodeManuallyEdited] = useState(false);

  // 自动生成的编码
  const autoGeneratedCode = useMemo(() => {
    if (mode === "edit" && initialData?.code) return initialData.code;
    return generateControlObjectiveCode({
      category: formData.category || "管理性",
      existingCodes: [],
    });
  }, [formData.category, mode, initialData?.code]);

  // 当自动生成编码变化且用户未手动编辑时，更新编码
  useEffect(() => {
    if (!isCodeManuallyEdited && !formData.code) {
      updateField("code", autoGeneratedCode);
    }
  }, [autoGeneratedCode, isCodeManuallyEdited]);

  // 验证表单
  const validate = useCallback(() => {
    const newErrors: Record<string, string> = {};

    if (!formData.code?.trim()) {
      newErrors.code = "请输入控制目标编码";
    } else if (!/^CO-[A-Z]{2,}-\d{3}$/.test(formData.code)) {
      newErrors.code = "编码格式应为 CO-XX-000 格式";
    }

    if (!formData.name?.trim()) {
      newErrors.name = "请输入控制目标名称";
    }

    if (!formData.description?.trim()) {
      newErrors.description = "请输入控制目标描述";
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  }, [formData]);

  // 提交表单
  const handleSubmit = useCallback(() => {
    if (!validate()) {
      toast.error("请完善表单信息");
      return;
    }

    const now = new Date().toISOString();
    const submittedData: ControlObjective = {
      ...(formData as ControlObjective),
      id: formData.id || `co-${Date.now()}`,
      createdAt: formData.createdAt || now,
      updatedAt: now,
    };

    onSubmit(submittedData);
  }, [formData, onSubmit, validate]);

  // 更新字段
  const updateField = useCallback(<K extends keyof ControlObjective>(
    field: K,
    value: ControlObjective[K]
  ) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    // 清除对应字段的错误
    if (errors[field]) {
      setErrors((prev) => ({ ...prev, [field]: undefined }));
    }
  }, [errors]);

  // 添加标准动作
  const addAction = useCallback(() => {
    const newAction: ActionRequirement = {
      actionCode: `ACT-${String(formData.standardActions?.length || 0 + 1).padStart(3, "0")}`,
      description: "",
      priority: "medium",
      isBlocking: false,
      checkPoints: [],
      deadline: "30天",
    };
    setFormData((prev) => ({
      ...prev,
      standardActions: [...(prev.standardActions || []), newAction],
    }));
  }, [formData.standardActions?.length]);

  // 更新标准动作
  const updateAction = useCallback((index: number, updates: Partial<ActionRequirement>) => {
    setFormData((prev) => ({
      ...prev,
      standardActions: prev.standardActions?.map((action, i) =>
        i === index ? { ...action, ...updates } : action
      ) || [],
    }));
  }, []);

  // 删除标准动作
  const removeAction = useCallback((index: number) => {
    setFormData((prev) => ({
      ...prev,
      standardActions: prev.standardActions?.filter((_, i) => i !== index) || [],
    }));
  }, []);

  // 更新五维标签
  const updateTags = useCallback((dimension: keyof FiveDimensionalTags, tags: string[]) => {
    setFormData((prev) => ({
      ...prev,
      applicableTags: {
        ...(prev.applicableTags || {
          objects: [],
          subjects: [],
          lifecycles: [],
          securities: [],
          actions: [],
        }),
        [dimension]: tags,
      },
    }));
  }, []);

  return (
    <div className="h-full flex flex-col bg-gradient-to-br from-slate-50 via-blue-50/20 to-slate-50">
      {/* 顶部工具栏 */}
      <div className="flex items-center justify-between px-6 py-4 bg-white/80 backdrop-blur-xl border-b border-slate-200/50">
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="sm" onClick={onCancel} className="gap-2">
            <ArrowLeft className="w-4 h-4" />
            返回
          </Button>
          <div className="h-6 w-px bg-slate-200" />
          <h1 className="text-lg font-semibold text-slate-800">
            {mode === "create" ? "创建控制目标" : "编辑控制目标"}
          </h1>
        </div>

        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" onClick={onCancel}>
            取消
          </Button>
          <Button size="sm" onClick={handleSubmit} className="gap-2">
            <Save className="w-4 h-4" />
            保存
          </Button>
        </div>
      </div>

      {/* 表单内容 */}
      <ScrollArea className="flex-1">
        <div className="max-w-4xl mx-auto p-6 space-y-6">
          {/* 基本信息 */}
          <Card>
            <CardHeader
              className="cursor-pointer"
              onClick={() => setExpandedSection(expandedSection === "basic" ? "" : "basic")}
            >
              <div className="flex items-center justify-between">
                <CardTitle className="text-base flex items-center gap-2">
                  <Target className="w-4 h-4 text-blue-500" />
                  基本信息
                </CardTitle>
                {expandedSection === "basic" ? (
                  <ChevronUp className="w-4 h-4 text-slate-400" />
                ) : (
                  <ChevronDown className="w-4 h-4 text-slate-400" />
                )}
              </div>
            </CardHeader>
            {expandedSection === "basic" && (
              <CardContent className="space-y-4">
                {/* 编码 */}
                <div>
                  <div className="flex items-center justify-between">
                    <label className="text-sm font-medium text-slate-700">
                      控制目标编码 <span className="text-red-500">*</span>
                    </label>
                    {mode === "create" && (
                      <button
                        onClick={() => {
                          setIsCodeManuallyEdited(false);
                          updateField("code", autoGeneratedCode);
                        }}
                        className="text-[10px] text-blue-500 hover:text-blue-700 flex items-center gap-0.5"
                      >
                        <Sparkles className="w-3 h-3" />
                        重新生成
                      </button>
                    )}
                  </div>
                  <Input
                    value={formData.code}
                    onChange={(e) => {
                      setIsCodeManuallyEdited(true);
                      updateField("code", e.target.value);
                    }}
                    placeholder={previewControlObjectiveCode(formData.category || "管理性")}
                    className={`mt-1 font-mono ${errors.code ? "border-red-500" : ""}`}
                  />
                  {errors.code ? (
                    <p className="text-xs text-red-500 mt-1">{errors.code}</p>
                  ) : (
                    <div className="text-xs text-slate-400 mt-1 flex items-center gap-1">
                      <span>格式: CO-</span>
                      <Badge variant="outline" className="text-[9px] px-1 py-0 h-4">
                        {formData.category === "预防性" ? "PR" :
                         formData.category === "检测性" ? "DE" :
                         formData.category === "纠正性" ? "CO" :
                         formData.category === "管理性" ? "MG" :
                         formData.category === "技术性" ? "TC" :
                         formData.category === "物理性" ? "PH" : "XX"}
                      </Badge>
                      <span>-000 (类别码自动匹配)</span>
                    </div>
                  )}
                </div>

                {/* 名称 */}
                <div>
                  <label className="text-sm font-medium text-slate-700">
                    控制目标名称 <span className="text-red-500">*</span>
                  </label>
                  <Input
                    value={formData.name}
                    onChange={(e) => updateField("name", e.target.value)}
                    placeholder="输入控制目标名称"
                    className={`mt-1 ${errors.name ? "border-red-500" : ""}`}
                  />
                  {errors.name && <p className="text-xs text-red-500 mt-1">{errors.name}</p>}
                </div>

                {/* 英文名称 */}
                <div>
                  <label className="text-sm font-medium text-slate-700">英文名称</label>
                  <Input
                    value={formData.nameEn || ""}
                    onChange={(e) => updateField("nameEn", e.target.value)}
                    placeholder="English name (optional)"
                    className="mt-1"
                  />
                </div>

                {/* 描述 */}
                <div>
                  <label className="text-sm font-medium text-slate-700">
                    详细描述 <span className="text-red-500">*</span>
                  </label>
                  <textarea
                    value={formData.description}
                    onChange={(e) => updateField("description", e.target.value)}
                    placeholder="详细描述该控制目标的要求和目的"
                    rows={4}
                    className={`w-full mt-1 p-3 rounded-md border ${
                      errors.description ? "border-red-500" : "border-slate-200"
                    } bg-transparent text-sm focus:outline-none focus:ring-2 focus:ring-blue-500`}
                  />
                  {errors.description && (
                    <p className="text-xs text-red-500 mt-1">{errors.description}</p>
                  )}
                </div>

                {/* 分类和域 */}
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="text-sm font-medium text-slate-700">控制类别</label>
                    <select
                      value={formData.category}
                      onChange={(e) => {
                        const newCategory = e.target.value as ControlCategory;
                        updateField("category", newCategory);
                        // 自动更新编码（如果用户未手动编辑）
                        if (!isCodeManuallyEdited) {
                          const newCode = generateControlObjectiveCode({
                            category: newCategory,
                            existingCodes: [],
                          });
                          updateField("code", newCode);
                        }
                      }}
                      className="w-full mt-1 p-2 rounded-md border border-slate-200 bg-white text-sm"
                    >
                      {CATEGORY_OPTIONS.map((opt) => (
                        <option key={opt.value} value={opt.value}>
                          {opt.label} - {opt.desc}
                        </option>
                      ))}
                    </select>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-slate-700">控制域</label>
                    <select
                      value={formData.domain}
                      onChange={(e) => updateField("domain", e.target.value)}
                      className="w-full mt-1 p-2 rounded-md border border-slate-200 bg-white text-sm"
                    >
                      {DOMAIN_OPTIONS.map((opt) => (
                        <option key={opt} value={opt}>
                          {opt}
                        </option>
                      ))}
                    </select>
                  </div>
                </div>

                {/* 重要性和权重 */}
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="text-sm font-medium text-slate-700">重要性级别</label>
                    <select
                      value={formData.importance}
                      onChange={(e) => updateField("importance", e.target.value as any)}
                      className="w-full mt-1 p-2 rounded-md border border-slate-200 bg-white text-sm"
                    >
                      {IMPORTANCE_OPTIONS.map((opt) => (
                        <option key={opt.value} value={opt.value}>
                          {opt.label} - {opt.desc}
                        </option>
                      ))}
                    </select>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-slate-700">
                      基础权重 (1-10)
                    </label>
                    <Input
                      type="number"
                      min={1}
                      max={10}
                      value={formData.baseWeight}
                      onChange={(e) => updateField("baseWeight", parseInt(e.target.value) || 5)}
                      className="mt-1"
                    />
                  </div>
                </div>
              </CardContent>
            )}
          </Card>

          {/* 五维标签 */}
          <Card>
            <CardHeader
              className="cursor-pointer"
              onClick={() => setExpandedSection(expandedSection === "tags" ? "" : "tags")}
            >
              <div className="flex items-center justify-between">
                <CardTitle className="text-base flex items-center gap-2">
                  <Layers className="w-4 h-4 text-purple-500" />
                  五维标签配置
                </CardTitle>
                {expandedSection === "tags" ? (
                  <ChevronUp className="w-4 h-4 text-slate-400" />
                ) : (
                  <ChevronDown className="w-4 h-4 text-slate-400" />
                )}
              </div>
            </CardHeader>
            {expandedSection === "tags" && (
              <CardContent className="space-y-4">
                <TagInput
                  label="客体维度 - 保护对象"
                  placeholder="如: OBJ-PI, OBJ-IMP, OBJ-COR"
                  tags={formData.applicableTags?.objects || []}
                  onChange={(tags) => updateTags("objects", tags)}
                  color="blue"
                />
                <TagInput
                  label="主体维度 - 责任主体"
                  placeholder="如: SUB-PRO, SUB-CII, SUB-GOV"
                  tags={formData.applicableTags?.subjects || []}
                  onChange={(tags) => updateTags("subjects", tags)}
                  color="green"
                />
                <TagInput
                  label="业务流转维度 - 业务环节"
                  placeholder="如: LIF-COL, LIF-STO, LIF-USE"
                  tags={formData.applicableTags?.lifecycles || []}
                  onChange={(tags) => updateTags("lifecycles", tags)}
                  color="orange"
                />
                <TagInput
                  label="安全域维度 - 保护手段"
                  placeholder="如: SEC-ENC, SEC-ACC, SEC-AUD"
                  tags={formData.applicableTags?.securities || []}
                  onChange={(tags) => updateTags("securities", tags)}
                  color="purple"
                />
                <TagInput
                  label="动作义务维度 - COU核心"
                  placeholder="如: ACT-DOC, ACT-TRA, ACT-AUD"
                  tags={formData.applicableTags?.actions || []}
                  onChange={(tags) => updateTags("actions", tags)}
                  color="red"
                />
              </CardContent>
            )}
          </Card>

          {/* 标准动作 */}
          <Card>
            <CardHeader
              className="cursor-pointer"
              onClick={() => setExpandedSection(expandedSection === "actions" ? "" : "actions")}
            >
              <div className="flex items-center justify-between">
                <CardTitle className="text-base flex items-center gap-2">
                  <CheckCircle className="w-4 h-4 text-green-500" />
                  标准动作要求
                  <Badge variant="secondary" className="text-xs">
                    {formData.standardActions?.length || 0}
                  </Badge>
                </CardTitle>
                {expandedSection === "actions" ? (
                  <ChevronUp className="w-4 h-4 text-slate-400" />
                ) : (
                  <ChevronDown className="w-4 h-4 text-slate-400" />
                )}
              </div>
            </CardHeader>
            {expandedSection === "actions" && (
              <CardContent className="space-y-4">
                {formData.standardActions?.map((action, index) => (
                  <ActionEditor
                    key={index}
                    action={action}
                    index={index}
                    onUpdate={(updates) => updateAction(index, updates)}
                    onRemove={() => removeAction(index)}
                  />
                ))}
                <Button
                  variant="outline"
                  className="w-full gap-2"
                  onClick={addAction}
                >
                  <Plus className="w-4 h-4" />
                  添加标准动作
                </Button>
              </CardContent>
            )}
          </Card>

          {/* 相关标准 */}
          <Card>
            <CardHeader
              className="cursor-pointer"
              onClick={() => setExpandedSection(expandedSection === "standards" ? "" : "standards")}
            >
              <div className="flex items-center justify-between">
                <CardTitle className="text-base flex items-center gap-2">
                  <Scale className="w-4 h-4 text-indigo-500" />
                  相关标准
                </CardTitle>
                {expandedSection === "standards" ? (
                  <ChevronUp className="w-4 h-4 text-slate-400" />
                ) : (
                  <ChevronDown className="w-4 h-4 text-slate-400" />
                )}
              </div>
            </CardHeader>
            {expandedSection === "standards" && (
              <CardContent>
                <div>
                  <label className="text-sm font-medium text-slate-700">
                    相关标准（用逗号分隔）
                  </label>
                  <Input
                    value={formData.standards?.join(", ") || ""}
                    onChange={(e) =>
                      updateField(
                        "standards",
                        e.target.value.split(",").map((s) => s.trim()).filter(Boolean)
                      )
                    }
                    placeholder="如: ISO27001-A.8.2.1, 等保2.0-8.1.4"
                    className="mt-1"
                  />
                </div>
                <div className="mt-4">
                  <label className="text-sm font-medium text-slate-700">
                    最佳实践参考（每行一条）
                  </label>
                  <textarea
                    value={formData.bestPractices?.join("\n") || ""}
                    onChange={(e) =>
                      updateField(
                        "bestPractices",
                        e.target.value.split("\n").map((s) => s.trim()).filter(Boolean)
                      )
                    }
                    placeholder="输入最佳实践参考..."
                    rows={4}
                    className="w-full mt-1 p-3 rounded-md border border-slate-200 bg-transparent text-sm"
                  />
                </div>
              </CardContent>
            )}
          </Card>
        </div>
      </ScrollArea>
    </div>
  );
}

// 标签输入组件
function TagInput({
  label,
  placeholder,
  tags,
  onChange,
  color,
}: {
  label: string;
  placeholder: string;
  tags: string[];
  onChange: (tags: string[]) => void;
  color: string;
}) {
  const [input, setInput] = useState("");

  const colorClasses: Record<string, string> = {
    blue: "bg-blue-100 text-blue-700 border-blue-200",
    green: "bg-green-100 text-green-700 border-green-200",
    orange: "bg-orange-100 text-orange-700 border-orange-200",
    purple: "bg-purple-100 text-purple-700 border-purple-200",
    red: "bg-red-100 text-red-700 border-red-200",
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" || e.key === ",") {
      e.preventDefault();
      const newTag = input.trim();
      if (newTag && !tags.includes(newTag)) {
        onChange([...tags, newTag]);
        setInput("");
      }
    }
    if (e.key === "Backspace" && !input && tags.length > 0) {
      onChange(tags.slice(0, -1));
    }
  };

  const removeTag = (tagToRemove: string) => {
    onChange(tags.filter((tag) => tag !== tagToRemove));
  };

  return (
    <div>
      <label className="text-sm font-medium text-slate-700">{label}</label>
      <div className="mt-1 p-2 rounded-md border border-slate-200 bg-white min-h-[42px] flex flex-wrap gap-1">
        {tags.map((tag) => (
          <Badge
            key={tag}
            variant="outline"
            className={`${colorClasses[color]} cursor-pointer`}
            onClick={() => removeTag(tag)}
          >
            {tag} ×
          </Badge>
        ))}
        <input
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder={tags.length === 0 ? placeholder : ""}
          className="flex-1 min-w-[100px] outline-none text-sm bg-transparent"
        />
      </div>
      <p className="text-xs text-slate-400 mt-1">按 Enter 或逗号添加标签</p>
    </div>
  );
}

// 动作编辑器组件
function ActionEditor({
  action,
  index,
  onUpdate,
  onRemove,
}: {
  action: ActionRequirement;
  index: number;
  onUpdate: (updates: Partial<ActionRequirement>) => void;
  onRemove: () => void;
}) {
  const [checkPointInput, setCheckPointInput] = useState("");
  const [deliverableInput, setDeliverableInput] = useState("");

  const addCheckPoint = () => {
    if (checkPointInput.trim()) {
      onUpdate({ checkPoints: [...action.checkPoints, checkPointInput.trim()] });
      setCheckPointInput("");
    }
  };

  const removeCheckPoint = (idx: number) => {
    onUpdate({ checkPoints: action.checkPoints.filter((_, i) => i !== idx) });
  };

  const addDeliverable = () => {
    if (deliverableInput.trim()) {
      onUpdate({
        deliverables: [...(action.deliverables || []), deliverableInput.trim()],
      });
      setDeliverableInput("");
    }
  };

  const removeDeliverable = (idx: number) => {
    onUpdate({
      deliverables: action.deliverables?.filter((_, i) => i !== idx) || [],
    });
  };

  return (
    <div className="p-4 rounded-lg border border-slate-200 bg-slate-50/50">
      <div className="flex items-center justify-between mb-3">
        <span className="text-sm font-medium text-slate-500">动作 #{index + 1}</span>
        <Button variant="ghost" size="sm" onClick={onRemove} className="h-8 w-8 p-0 text-red-500">
          <Trash2 className="w-4 h-4" />
        </Button>
      </div>

      <div className="space-y-3">
        {/* 动作编码和描述 */}
        <div className="grid grid-cols-3 gap-3">
          <Input
            value={action.actionCode}
            onChange={(e) => onUpdate({ actionCode: e.target.value })}
            placeholder="动作编码"
            className="col-span-1"
          />
          <Input
            value={action.description}
            onChange={(e) => onUpdate({ description: e.target.value })}
            placeholder="动作描述"
            className="col-span-2"
          />
        </div>

        {/* 优先级、期限、阻断性 */}
        <div className="grid grid-cols-3 gap-3">
          <select
            value={action.priority}
            onChange={(e) => onUpdate({ priority: e.target.value as ActionPriority })}
            className="p-2 rounded-md border border-slate-200 bg-white text-sm"
          >
            {PRIORITY_OPTIONS.map((opt) => (
              <option key={opt.value} value={opt.value}>
                {opt.label}优先级
              </option>
            ))}
          </select>
          <Input
            value={action.deadline}
            onChange={(e) => onUpdate({ deadline: e.target.value })}
            placeholder="期限 (如: 30天)"
          />
          <label className="flex items-center gap-2 p-2">
            <input
              type="checkbox"
              checked={action.isBlocking}
              onChange={(e) => onUpdate({ isBlocking: e.target.checked })}
              className="rounded border-slate-300"
            />
            <span className="text-sm text-slate-700">阻断性要求</span>
          </label>
        </div>

        {/* 检查点 */}
        <div>
          <label className="text-xs text-slate-500">检查点</label>
          <div className="flex flex-wrap gap-1 mt-1">
            {action.checkPoints.map((point, idx) => (
              <Badge
                key={idx}
                variant="secondary"
                className="text-xs cursor-pointer"
                onClick={() => removeCheckPoint(idx)}
              >
                {point} ×
              </Badge>
            ))}
            <div className="flex items-center gap-1">
              <Input
                value={checkPointInput}
                onChange={(e) => setCheckPointInput(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && addCheckPoint()}
                placeholder="添加检查点"
                className="h-7 text-xs w-32"
              />
              <Button variant="ghost" size="sm" onClick={addCheckPoint} className="h-7 w-7 p-0">
                <Plus className="w-3 h-3" />
              </Button>
            </div>
          </div>
        </div>

        {/* 交付物 */}
        <div>
          <label className="text-xs text-slate-500">交付物</label>
          <div className="flex flex-wrap gap-1 mt-1">
            {action.deliverables?.map((item, idx) => (
              <Badge
                key={idx}
                variant="outline"
                className="text-xs cursor-pointer bg-blue-50"
                onClick={() => removeDeliverable(idx)}
              >
                {item} ×
              </Badge>
            ))}
            <div className="flex items-center gap-1">
              <Input
                value={deliverableInput}
                onChange={(e) => setDeliverableInput(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && addDeliverable()}
                placeholder="添加交付物"
                className="h-7 text-xs w-32"
              />
              <Button variant="ghost" size="sm" onClick={addDeliverable} className="h-7 w-7 p-0">
                <Plus className="w-3 h-3" />
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default ControlObjectiveForm;
