// ============ COU拆解工作台 ============
// 核心功能：将法律条文拆解为可执行的原子级COU

import React, { useState, useCallback, useMemo } from "react";
import {
  Save,
  Wand2,
  FileText,
  ChevronRight,
  ChevronDown,
  Plus,
  Trash2,
  AlertCircle,
  CheckCircle,
  Clock,
  Target,
  Layers,
  Sparkles,
  Briefcase,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "../ui/card";
import { Button } from "../ui/button";
import { Input } from "../ui/input";
import { Label } from "../ui/label";
import { Badge } from "../ui/badge";
import { Textarea } from "../ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../ui/tabs";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "../ui/select";
import { Separator } from "../ui/separator";
import { ScrollArea } from "../ui/scroll-area";
import type {
  COU,
  ActionRequirement,
  FiveDimensionalTags,
  PolicyLevel,
  PenaltyLevel,
} from "../../types";
import { POLICY_LEVEL_WEIGHTS, PENALTY_WEIGHTS } from "../../types";
import { MOCK_POLICIES, MOCK_CLAUSES } from "../../data/mockData";
import {
  createEmptyFiveDimensionalTags,
  validateFiveDimensionalTags,
} from "../../services/tagMatching";
import {
  generateCOUCode,
  previewCOUCode,
  generatePolicyShortCode,
} from "../../services/codeGenerator";
import { ActionRequirementForm, createEmptyActionRequirement } from "./ActionRequirementForm";
import { FiveDimensionalTagSelector } from "./FiveDimensionalTagSelector";

// ============ 模拟LLM拆解结果 ============
const MOCK_LLM_RESULT = {
  confidence: 0.87,
  suggestedCOU: {
    title: "建立全流程数据安全管理制度",
    description:
      "根据《数据安全法》第27条，开展数据处理活动应当建立健全全流程数据安全管理制度",
    fiveDimensionalTags: {
      objects: ["OBJ-IMP", "OBJ-COR"],
      subjects: ["SUB-PRO", "SUB-CII"],
      lifecycles: ["LIF-COL", "LIF-STO", "LIF-USE", "LIF-PRO"],
      securities: ["SEC-ORG"],
      actions: ["ACT-DOC", "ACT-AUD"],
    },
    actionRequirements: [
      {
        actionCode: "ACT-DOC",
        description: "建立数据安全管理制度文件",
        deadline: "30天",
        priority: "high" as const,
        isBlocking: false,
        checkPoints: [
          "制定数据分类分级制度",
          "建立数据安全应急预案",
          "明确数据安全责任部门",
        ],
        deliverables: ["数据安全管理制度文件"],
      },
      {
        actionCode: "ACT-AUD",
        description: "定期开展数据安全审计",
        deadline: "年度",
        priority: "medium" as const,
        isBlocking: false,
        checkPoints: ["制定审计计划", "执行审计程序", "形成审计报告"],
        deliverables: ["年度数据安全审计报告"],
      },
    ],
  },
};

interface COUWorkbenchProps {
  initialCOU?: COU;
  onSave?: (cou: COU) => void;
  className?: string;
}

export function COUWorkbench({
  initialCOU,
  onSave,
  className = "",
}: COUWorkbenchProps) {
  // ============ 状态管理 ============
  const [selectedPolicyId, setSelectedPolicyId] = useState<string>(
    initialCOU?.policyId || ""
  );
  const [selectedClauseId, setSelectedClauseId] = useState<string>(
    initialCOU?.sourceClauseId || ""
  );
  const [selectedText, setSelectedText] = useState<string>("");

  // COU表单状态
  const [couCode, setCouCode] = useState(initialCOU?.code || "");
  const [couTitle, setCouTitle] = useState(initialCOU?.title || "");
  const [couDescription, setCouDescription] = useState(
    initialCOU?.description || ""
  );
  const [obligationType, setObligationType] = useState<
    COU["obligationType"]
  >(initialCOU?.obligationType || "强制性");
  const [actionRequired, setActionRequired] = useState(
    initialCOU?.actionRequired || ""
  );
  const [deadline, setDeadline] = useState(initialCOU?.deadline || "");
  const [penalty, setPenalty] = useState(initialCOU?.penalty || "");
  const [penaltyLevel, setPenaltyLevel] = useState<PenaltyLevel>(
    initialCOU?.penaltyLevel || "无"
  );

  // 五维标签
  const [fiveDimTags, setFiveDimTags] = useState<FiveDimensionalTags>(
    initialCOU?.fiveDimensionalTags || createEmptyFiveDimensionalTags()
  );

  // 动作义务
  const [actionRequirements, setActionRequirements] = useState<
    ActionRequirement[]
  >(initialCOU?.actionRequirements || []);

  // LLM辅助状态
  const [isLLMLoading, setIsLLMLoading] = useState(false);
  const [llmConfidence, setLLMConfidence] = useState<number | null>(null);

  // 验证状态
  const [validationErrors, setValidationErrors] = useState<string[]>([]);

  // ============ 派生数据 ============
  const selectedPolicy = useMemo(
    () => MOCK_POLICIES.find((p) => p.id === selectedPolicyId),
    [selectedPolicyId]
  );

  // 自动生成的COU编码
  const autoGeneratedCode = useMemo(() => {
    if (initialCOU?.code) return initialCOU.code;
    return generateCOUCode({
      policy: selectedPolicy,
      // 实际项目中应从已有COU数据获取
      existingCodes: [],
    });
  }, [selectedPolicy, initialCOU]);

  // 当自动编码变化且用户未手动编辑时，更新编码
  React.useEffect(() => {
    if (!couCode || couCode === previewCOUCode(selectedPolicy)) {
      setCouCode(autoGeneratedCode);
    }
  }, [autoGeneratedCode, selectedPolicy]);

  const policyClauses = useMemo(
    () => MOCK_CLAUSES.filter((c) => c.policyId === selectedPolicyId),
    [selectedPolicyId]
  );

  const selectedClause = useMemo(
    () => MOCK_CLAUSES.find((c) => c.id === selectedClauseId),
    [selectedClauseId]
  );

  // ============ 事件处理 ============
  const handleAddActionRequirement = useCallback(() => {
    setActionRequirements([...actionRequirements, createEmptyActionRequirement()]);
  }, [actionRequirements]);

  const handleUpdateActionRequirement = useCallback(
    (index: number, updated: ActionRequirement) => {
      const newRequirements = [...actionRequirements];
      newRequirements[index] = updated;
      setActionRequirements(newRequirements);
    },
    [actionRequirements]
  );

  const handleRemoveActionRequirement = useCallback(
    (index: number) => {
      setActionRequirements(actionRequirements.filter((_, i) => i !== index));
    },
    [actionRequirements]
  );

  // LLM辅助拆解
  const handleLLMAssist = useCallback(async () => {
    if (!selectedText && !selectedClause) return;

    setIsLLMLoading(true);

    // 模拟API调用延迟
    await new Promise((resolve) => setTimeout(resolve, 1500));

    // 应用LLM建议
    const result = MOCK_LLM_RESULT;
    setCouTitle(result.suggestedCOU.title);
    setCouDescription(result.suggestedCOU.description);
    setFiveDimTags(result.suggestedCOU.fiveDimensionalTags);
    setActionRequirements(result.suggestedCOU.actionRequirements);
    setLLMConfidence(result.confidence);

    setIsLLMLoading(false);
  }, [selectedText, selectedClause]);

  // 验证表单
  const validateForm = useCallback((): boolean => {
    const errors: string[] = [];

    if (!couCode.trim()) errors.push("COU编号不能为空");
    if (!couTitle.trim()) errors.push("标题不能为空");
    if (!selectedPolicyId) errors.push("请选择来源政策");
    if (!selectedClauseId) errors.push("请选择来源条款");

    const tagValidation = validateFiveDimensionalTags(fiveDimTags);
    if (!tagValidation.valid) {
      errors.push(...tagValidation.errors.filter((e) => !e.startsWith("警告")));
    }

    setValidationErrors(errors);
    return errors.length === 0;
  }, [
    couCode,
    couTitle,
    selectedPolicyId,
    selectedClauseId,
    fiveDimTags,
  ]);

  // 保存COU
  const handleSave = useCallback(
    (isDraft: boolean = false) => {
      if (!validateForm()) return;

      const newCOU: COU = {
        id: initialCOU?.id || `cou-${Date.now()}`,
        code: couCode,
        title: couTitle,
        description: couDescription,
        sourceClauseId: selectedClauseId,
        policyId: selectedPolicyId,
        policyTitle: selectedPolicy?.title || "",
        policyLevel: (selectedPolicy?.level || "部门规章") as PolicyLevel,
        obligationType,
        actionRequired,
        deadline: deadline || undefined,
        penalty: penalty || undefined,
        penaltyLevel,
        baseWeight: POLICY_LEVEL_WEIGHTS[selectedPolicy?.level || "部门规章"],
        penaltyWeight: PENALTY_WEIGHTS[penaltyLevel],
        tagMatchScore: 0,
        scenarioWeight: 0,
        finalWeight: 0,
        tags: [],
        fiveDimensionalTags: fiveDimTags,
        tagWeights: {},
        autoTags: [],
        actionRequirements,
        applicableIndustries: ["通用"],
        applicableRegions: ["国内"],
        applicableUserTypes: ["大型企业"],
        version: "1.0",
        status: isDraft ? "revised" : "current",
        createdAt: initialCOU?.createdAt || new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        llmMetadata: llmConfidence
          ? {
              decompositionConfidence: llmConfidence,
              aiSuggestions: ["建议人工复核动作义务定义"],
            }
          : undefined,
      };

      onSave?.(newCOU);
    },
    [
      validateForm,
      couCode,
      couTitle,
      couDescription,
      selectedClauseId,
      selectedPolicyId,
      selectedPolicy,
      obligationType,
      actionRequired,
      deadline,
      penalty,
      penaltyLevel,
      fiveDimTags,
      actionRequirements,
      initialCOU,
      llmConfidence,
      onSave,
    ]
  );

  return (
    <div className={`h-full flex flex-col bg-gradient-to-br from-slate-50 via-blue-50/30 to-slate-50 ${className}`}>
      {/* 顶部工具栏 */}
      <div className="flex items-center justify-between px-6 py-4 bg-white/80 backdrop-blur-xl border-b border-slate-200/50">
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2">
            <div className="size-10 rounded-xl bg-gradient-to-br from-blue-500 to-cyan-500 flex items-center justify-center shadow-lg shadow-blue-500/30">
              <Briefcase className="w-5 h-5 text-white" />
            </div>
            <h1 className="text-lg font-semibold text-slate-800">
              COU拆解工作台
            </h1>
          </div>
          {llmConfidence !== null && (
            <Badge
              variant="outline"
              className={`${
                llmConfidence >= 0.8
                  ? "bg-green-100 text-green-700 border-green-200"
                  : llmConfidence >= 0.6
                  ? "bg-yellow-100 text-yellow-700 border-yellow-200"
                  : "bg-red-100 text-red-700 border-red-200"
              }`}
            >
              AI置信度: {Math.round(llmConfidence * 100)}%
            </Badge>
          )}
        </div>
        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            onClick={() => handleSave(true)}
          >
            <Clock className="w-4 h-4 mr-2" />
            保存草稿
          </Button>
          <Button
            onClick={() => handleSave(false)}
            className="bg-gradient-to-r from-blue-600 to-cyan-600 hover:from-blue-700 hover:to-cyan-700"
          >
            <Save className="w-4 h-4 mr-2" />
            发布COU
          </Button>
        </div>
      </div>

      {/* 验证错误提示 */}
      {validationErrors.length > 0 && (
        <div className="px-6 py-3 bg-red-50 border-b border-red-100">
          <div className="flex items-start gap-2">
            <AlertCircle className="w-5 h-5 text-red-500 mt-0.5" />
            <div className="flex-1">
              <div className="text-sm font-medium text-red-700 mb-1">
                请修复以下问题：
              </div>
              <ul className="text-sm text-red-600 space-y-0.5">
                {validationErrors.map((error, idx) => (
                  <li key={idx}>• {error}</li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      )}

      {/* 主内容区 */}
      <div className="flex-1 flex overflow-hidden">
        {/* 左侧：原文视图 */}
        <div className="w-1/2 flex flex-col border-r border-slate-200/50 bg-white/40">
          <div className="p-4 bg-white/60 backdrop-blur-xl border-b border-slate-200/50">
            <div className="grid grid-cols-2 gap-3 mb-3">
              <div>
                <Label className="text-slate-600 text-xs mb-1.5 block">
                  来源政策
                </Label>
                <Select
                  value={selectedPolicyId}
                  onValueChange={(v) => {
                    setSelectedPolicyId(v);
                    setSelectedClauseId("");
                  }}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="选择政策文件" />
                  </SelectTrigger>
                  <SelectContent>
                    {MOCK_POLICIES.map((policy) => (
                      <SelectItem
                        key={policy.id}
                        value={policy.id}
                      >
                        {policy.title}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div>
                <Label className="text-slate-600 text-xs mb-1.5 block">
                  来源条款
                </Label>
                <Select
                  value={selectedClauseId}
                  onValueChange={setSelectedClauseId}
                  disabled={!selectedPolicyId}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="选择条款" />
                  </SelectTrigger>
                  <SelectContent className="max-h-[300px]">
                    {policyClauses.map((clause) => (
                      <SelectItem
                        key={clause.id}
                        value={clause.id}
                      >
                        {clause.chapter} {clause.article}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>

            {/* LLM辅助按钮 */}
            <Button
              variant="outline"
              onClick={handleLLMAssist}
              disabled={isLLMLoading || (!selectedClause && !selectedText)}
              className="w-full border-purple-200 text-purple-700 hover:bg-purple-50 hover:text-purple-800 bg-purple-50/50"
            >
              {isLLMLoading ? (
                <>
                  <Sparkles className="w-4 h-4 mr-2 animate-pulse" />
                  AI分析中...
                </>
              ) : (
                <>
                  <Wand2 className="w-4 h-4 mr-2" />
                  AI辅助拆解
                </>
              )}
            </Button>
          </div>

          {/* 条款内容 */}
          <ScrollArea className="flex-1 p-4">
            {selectedClause ? (
              <div className="space-y-4">
                <div className="flex items-center gap-2 text-sm text-slate-500">
                  <FileText className="w-4 h-4" />
                  <span>
                    {selectedClause.chapter} {selectedClause.article}
                  </span>
                </div>
                <div
                  className="text-slate-700 leading-relaxed whitespace-pre-wrap cursor-text select-text bg-white/60 p-4 rounded-lg border border-slate-200/50"
                  onMouseUp={() => {
                    const selection = window.getSelection()?.toString();
                    if (selection) setSelectedText(selection);
                  }}
                >
                  {selectedClause.content}
                </div>
                {selectedText && (
                  <div className="p-3 bg-purple-50 border border-purple-200 rounded-lg">
                    <div className="text-xs text-purple-600 mb-1">
                      已选文本（点击AI辅助拆解以分析）：
                    </div>
                    <div className="text-sm text-slate-700 line-clamp-3">
                      {selectedText}
                    </div>
                  </div>
                )}
              </div>
            ) : (
              <div className="h-full flex items-center justify-center text-slate-400">
                <div className="text-center">
                  <FileText className="w-12 h-12 mx-auto mb-3 opacity-50" />
                  <p>请选择政策和条款开始拆解</p>
                </div>
              </div>
            )}
          </ScrollArea>
        </div>

        {/* 右侧：COU编辑表单 */}
        <div className="w-1/2 flex flex-col bg-white/20 h-full overflow-hidden">
          <ScrollArea className="flex-1 p-6 overflow-y-auto">
            <div className="space-y-6">
              {/* 基本信息 */}
              <Card>
                <CardHeader className="pb-3">
                  <CardTitle className="text-sm flex items-center gap-2">
                    <Layers className="w-4 h-4 text-blue-500" />
                    基本信息
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label className="text-slate-600 text-xs flex items-center justify-between">
                        <span>COU编号</span>
                        {selectedPolicy && (
                          <button
                            onClick={() => setCouCode(autoGeneratedCode)}
                            className="text-[10px] text-blue-500 hover:text-blue-700 flex items-center gap-0.5"
                          >
                            <Sparkles className="w-3 h-3" />
                            重新生成
                          </button>
                        )}
                      </Label>
                      <Input
                        value={couCode}
                        onChange={(e) => setCouCode(e.target.value)}
                        placeholder={selectedPolicy ? autoGeneratedCode : "请先选择来源政策"}
                        disabled={!selectedPolicy}
                        className="font-mono text-sm"
                      />
                      {selectedPolicy && (
                        <div className="text-[10px] text-slate-400 flex items-center gap-1">
                          <span>基于政策简码</span>
                          <Badge variant="outline" className="text-[9px] px-1 py-0 h-4">
                            {generatePolicyShortCode(selectedPolicy.title)}
                          </Badge>
                          <span>自动生成</span>
                        </div>
                      )}
                    </div>
                    <div className="space-y-2">
                      <Label className="text-slate-600 text-xs">合规类型</Label>
                      <Select
                        value={obligationType}
                        onValueChange={(v) =>
                          setObligationType(v as COU["obligationType"])
                        }
                      >
                        <SelectTrigger>
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          {["禁止性", "强制性", "推荐性", "指导性"].map(
                            (type) => (
                              <SelectItem
                                key={type}
                                value={type}
                              >
                                {type}
                              </SelectItem>
                            )
                          )}
                        </SelectContent>
                      </Select>
                    </div>
                  </div>

                  <div className="space-y-2">
                    <Label className="text-slate-600 text-xs">标题</Label>
                    <Input
                      value={couTitle}
                      onChange={(e) => setCouTitle(e.target.value)}
                      placeholder="简短描述合规义务"
                    />
                  </div>

                  <div className="space-y-2">
                    <Label className="text-slate-600 text-xs">详细描述</Label>
                    <Textarea
                      value={couDescription}
                      onChange={(e) => setCouDescription(e.target.value)}
                      placeholder="详细描述合规要求..."
                      className="min-h-[80px]"
                    />
                  </div>

                  <div className="space-y-2">
                    <Label className="text-slate-600 text-xs">要求的行动</Label>
                    <Input
                      value={actionRequired}
                      onChange={(e) => setActionRequired(e.target.value)}
                      placeholder="如：建立数据安全管理制度、开展安全评估等"
                    />
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label className="text-slate-600 text-xs">期限要求</Label>
                      <Input
                        value={deadline}
                        onChange={(e) => setDeadline(e.target.value)}
                        placeholder="如：30天、立即、年度"
                      />
                    </div>
                    <div className="space-y-2">
                      <Label className="text-slate-600 text-xs">罚则力度</Label>
                      <Select
                        value={penaltyLevel}
                        onValueChange={(v) => setPenaltyLevel(v as PenaltyLevel)}
                      >
                        <SelectTrigger>
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          {Object.entries(PENALTY_WEIGHTS).map(
                            ([level, weight]) => (
                              <SelectItem
                                key={level}
                                value={level}
                              >
                                {level} (权重{weight})
                              </SelectItem>
                            )
                          )}
                        </SelectContent>
                      </Select>
                    </div>
                  </div>

                  <div className="space-y-2">
                    <Label className="text-slate-600 text-xs">违规后果</Label>
                    <Textarea
                      value={penalty}
                      onChange={(e) => setPenalty(e.target.value)}
                      placeholder="描述违规后的法律责任..."
                      className="min-h-[60px]"
                    />
                  </div>
                </CardContent>
              </Card>

              {/* 五维标签选择 */}
              <Card>
                <CardHeader className="pb-3">
                  <CardTitle className="text-sm flex items-center gap-2">
                    <Target className="w-4 h-4 text-blue-500" />
                    五维标签
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <FiveDimensionalTagSelector
                    value={fiveDimTags}
                    onChange={setFiveDimTags}
                    showPreview={true}
                  />
                </CardContent>
              </Card>

              {/* 动作义务定义 */}
              <Card>
                <CardHeader className="pb-3">
                  <div className="flex items-center justify-between">
                    <CardTitle className="text-sm flex items-center gap-2">
                      <CheckCircle className="w-4 h-4 text-blue-500" />
                      动作义务定义
                      <Badge
                        variant="outline"
                        className="text-xs bg-red-100 text-red-700 border-red-200"
                      >
                        核心
                      </Badge>
                    </CardTitle>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={handleAddActionRequirement}
                    >
                      <Plus className="w-4 h-4 mr-1" />
                      添加动作
                    </Button>
                  </div>
                </CardHeader>
                <CardContent className="space-y-4">
                  {actionRequirements.length === 0 ? (
                    <div className="text-center py-8 text-slate-400 border border-dashed border-slate-200 rounded-lg">
                      <AlertCircle className="w-8 h-8 mx-auto mb-2 opacity-50" />
                      <p className="text-sm">暂无动作义务定义</p>
                      <p className="text-xs mt-1">
                        点击上方按钮添加或点击左侧"AI辅助拆解"
                      </p>
                    </div>
                  ) : (
                    actionRequirements.map((req, index) => (
                      <ActionRequirementForm
                        key={index}
                        value={req}
                        onChange={(updated) =>
                          handleUpdateActionRequirement(index, updated)
                        }
                        onDelete={() => handleRemoveActionRequirement(index)}
                      />
                    ))
                  )}
                </CardContent>
              </Card>
            </div>
          </ScrollArea>
        </div>
      </div>
    </div>
  );
}

export default COUWorkbench;
